name: Continuous integration
on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install dependency
        run: pip install --user sphinx==1.5.6 sphinxcontrib-versioning sphinx_rtd_theme

      - name: Build
        run: make html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html_build
          publish_branch: gh-pages
          force_orphan: true